# Generated by Django 5.1.3 on 2024-11-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='site',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
